
<link rel="stylesheet" href="https://revolus.com/assets/css/style.css">
<link rel="stylesheet" href="https://revolus.com/assets/css/font-awesome-4.7.0/css/font-awesome.min.css">
<?php
   $postImages = postAlbumImages($_GET['post_id']);
   
  $postIds = null;
  if(isset($_GET['post_ids']) && !empty($_GET['post_ids'])){
      $postIds = implode(",",$_GET['post_ids']);
      
  }
$query = $wo['story']['id'];
$image = Wo_GetMedia($wo['story']['postFile']);
if (strpos($wo['story']['postFile'],',') !== false) {
    $explode = @explode(',', $wo['story']['postFile']);
    $image = Wo_GetMedia($explode[0]);
}
if ($wo['config']['shout_box_system'] == 1 && $wo['story']['postPrivacy'] == 4) {
      $anonymous = true;
      $wo['story']['publisher']['username'] = 'anonymous';
      $wo['story']['publisher']['name'] = $wo['lang']['anonymous'];
      $wo['story']['publisher']['avatar'] = Wo_GetMedia('upload/photos/incognito.png');
      $wo['story']['publisher']['verified'] = 0;
      $wo['story']['publisher']['type'] = '';
	  $wo['story']['publisher']['url'] = 'javascript:void(0)';
   }
if(!empty($postIds)){

     
 //$photo_stories = Wo_GetPostsV2(array('filter_by' => 'photos','after_post_id' => 0, 'page_id' => 0, 'group_id' => 0, 'publisher_id' => 0, 'limit' => 100, 'event_id' => 0, 'ad-id' => 0,'post_ids' => $postIds));      
}else{
 //$photo_stories = Wo_GetPosts(array('filter_by' => 'photos','limit' => 100, 'publisher_id' => $wo['user_profile']['user_id']));       
}   


?>

<style>
    #fb5 #fb5-book .turn-page {
        background-size: contain;
        background-repeat: no-repeat;
        background-position: center;
        background-color: #f5f5f5 !important;
    }
    #fb5-ajax.fullScreen, #fb5-ajax[data-template="true"]{
        right: 0px !important;
        max-width: 80%;
    }
    #fb5 .fb5-menu#fb5-center ul li{
        display: block;
        width: 100%;
    }
    #fb5 .fb5-menu#fb5-center{
        width: auto;
        background: black;
        margin-top: 9px;
        position: absolute;
        right: 0px !important;
        max-width: 40px;
        left: auto !important;
        top: 250px;
    }
    
    #fb5 .fb5-menu#fb5-left ul li{
        display: block;
        width: 100%;
        margin-bottom: 10px;
    }
    #fb5 .fb5-menu#fb5-left{
        width: auto;
        background: black;
        margin-top: 9px;
        position: absolute;
        left: 0px !important;
        max-width: 100px;
        top: 200px;
        right: 0px;
        display: none;
    }
    #wo_post_stat_button .stat-item {
        border-radius: 100% !important;
        border: 2px solid #cccccc !important;
        color: #000;
        font-size: 11px;
        font-weight: 700;
        max-width: 45px;
        line-height: 0px;
        flex: 1;
        border: 0;
        box-shadow: none;
        padding: 0px !important;
        line-height: 45px;
        background: #FFF !important;
        top: 10px;
        transition: all .1s ease-in-out;
        cursor: pointer;
        height: 42px;
        width: 45px;
        margin-bottom: 10px !important;
        transition: 0.3s;
    }
    .btn-default svg.feather {
        margin-top: -3px;
        display: block;
        /* width: 16px; */
        margin-left: 12px;
        margin-top: 12px;
        /* height: 16px; */
        /* padding: 0px 12px !important; */
    }
    #wo_post_stat_button .stat-item:hover {
        background: white !important;
        color: black;
        transition: 0.3s;
    }
    #wo_post_stat_button .dropdown.open .stat-item, #wo_post_stat_button .stat-item:hover {
        border-radius: 0px;
        background: white;
    }
    .mb-10{
        margin-bottom: 10px !important;
    }
    .wo-reaction{
        padding: 6px 11px !important;
        border-radius: 3px !important;
        background: #ebeef0 !important;
    }
    
    .fb5-overlay.active{
            z-index: 999999;
    }
    .wo_imagecombo_lbox .comment-section{
        max-width: 20%;
    }
    html .icon-rounded{
        border: 2px solid #f5f5f5 !important;
        width: 30px !important;
        height: 30px !important;
        padding: 1px !important;
        margin-right: 0px !important;
        padding-right: 0px !important;
        font-size: 16px !important;
        text-align: center !important;
        line-height: 35px !important;
        border-radius: 100% !important;
    }
    .reactions-box{
        left: 40px;
        z-index: 999999;
        top: -20px;
        width: 292px;
    }
    .stat-item.follow{
        position: absolute;
        top: 200px;
        background: url(https://revolus.com/upload/photos/d-avatar.jpg?cache=0) no-repeat !important;
        z-index: 999999;
        background-size: cover !important;
        border-radius: 100% !important;
        border: 2px solid #cccccc !important;
        color: #000;
        font-size: 11px;
        font-weight: 700;
        line-height: 0px;
        flex: 1;
        border: 0;
        box-shadow: none;
        padding: 0px !important;
        line-height: 45px !important;
        cursor: pointer;
        height: 42px;
        width: 45px;
        transition: 0.3s;
        left: 5px;
    }
    .comment-inner-middle {
        position: absolute;
        top: 240px;
        z-index: 999999;
        border-radius: 4px;
        left: 4px;
    }
    
    .stat-item.follow:hover {
        /*background: white !important;*/
        /*color: black;*/
        /*transition: 0.3s;*/
    }
    .stat-item.share{
        position: absolute;
        top: 300px;
        z-index: 999999;
        border-radius: 100% !important;
        border: 2px solid #cccccc !important;
        color: #000;
        font-size: 11px;
        font-weight: 700;
        line-height: 0px;
        flex: 1;
        border: 0;
        box-shadow: none;
        padding: 0px !important;
        line-height: 45px !important;
        background: #FFF !important;
        cursor: pointer;
        height: 42px;
        width: 45px;
        transition: 0.3s;
        left: 5px;
    }
    .stat-item.share:hover {
        background: white !important;
        color: black;
        transition: 0.3s;
    }
    .stat-item.comment{
        position: absolute;
        top: 350px;
        z-index: 999999;
        border-radius: 100% !important;
        border: 2px solid #cccccc !important;
        color: #000;
        font-size: 11px;
        font-weight: 700;
        line-height: 0px;
        flex: 1;
        border: 0;
        box-shadow: none;
        line-height: 45px !important;
        padding: 0px !important;
        background: #FFF !important;
        cursor: pointer;
        height: 42px;
        width: 45px;
        transition: 0.3s;
        left: 5px;
    }
    .stat-item.comment:hover {
        background: white !important;
        color: black;
        transition: 0.3s;
    }
    
    .inline_post_emoji{
        margin-right: 1px !important;
    }
    #fb5 #fb5-book .turn-page{
        background-color: transparent !important;
    }
    #fb5 .turn-page.even .fb5-cont-page-book > .fb5-gradient-page{
        background: none !important;
    }
    .fb5-menu ul li a{ transition: 0.3s;transform:scale(1); }
    .fb5-menu ul li a:hover{ transition: 0.3s;transform:scale(1.3); }
    .turn-page-wrapper{
        box-shadow:0 0 1px 0px #cccccc!important;
        /*0 0 40px rgb(102 102 102 / 80%)*/
    }
    
    
    .sliderUl{
        height: 110px;
        width: 100%;
        margin: 0 auto;
        display: block;
        overflow: scroll hidden !important;
        margin-left: auto;
        margin-right: auto;
        max-width: 100%;
        z-index: 100000000;
        bottom: 0px;
        position: absolute;
        display: none;
    }
    .sliderUl ul{
        white-space:nowrap;
    }
    .sliderUl ul li
    {
        margin-right: 15px;
        display: inline;
        font-size: 12px;
        list-style-type: none;
    }
    .sliderUl ul li img{
        max-height: 100px;
        cursor: pointer;
    }
    .sliderUl::-webkit-scrollbar {
      width: 4px !important;
    height: 4px !important;
    }
    .sliderUl::-webkit-scrollbar-track {
      background: #f1f1f1; 
    }
    .sliderUl::-webkit-scrollbar-thumb {
      background: #888; 
    }
    .sliderUl::-webkit-scrollbar-thumb:hover {
      background: #555; 
    }
    #fb5 #fb5-container-book{
        /*position: initial;*/
    }
    #fb5-book{
        top: -55px;
    }
    #fb5 #fb5-all-pages .fb5-container-pages {
        background: black;
        /*box-shadow: 0 0 40px rgb(102 102 102 / 80%);*/
        box-shadow: none;
        bottom: 0px;
        top: auto !important;
        height: 60px !important;
        display: block !important;
        z-index: 99;
    }
    #fb5 .fb5-overlay{
        position: unset;
        top: auto;
        z-index: 10;
    }
    #fb5 .fb5-overlay.active{
        background: none;
    }
    #fb5 .turn-page.odd .fb5-cont-page-book > .fb5-gradient-page{
        box-shadow: none;
        background: none;
    }
    #perImageModal .comment-inner-middle{
        top: 140px;
    }
    #perImageModal .stat-item.follow{
        top: 50px;
    }
    #perImageModal .stat-item.share{
        top: 100px;
    }
    #perImageModal .stat-item.comment{
        top: 200px;
    }
    #perImageModal .like-btn{
        top: -3px;
        font-size: 8px !important;
    }
    #perImageModal .modal-dialog{
        width: 1000px;
    }
    .stat-item.follow button {
        position: absolute;
        padding: 8px 5px;
        line-height: 0px;
        border-radius: 10px;
        background: white;
        text-align: center;
        border: none;
        top: -5px;
        height: 18px;
        width: 18px;
        right: -5px;
        box-shadow: 2px 1px 12px #f2f3f5;
    }
    #fb5 #fb5-slider {
        position: absolute;
        left: 0;
        width: 100% !important;
        list-style: none;
        height: inherit; 
        display: flex;
        vertical-align: middle;
        align-items: center;
        margin: 0 auto;
        display: flex;
        justify-content: center;
    }
    #perImageModal button.close {
        position: absolute;
        right: 0px;
        color: black;
        background: white;
        opacity: 1;
        height: 30px;
        width: 30px;
        line-height: 0px;
        z-index: 999999;
    }
    .p-0{
        padding: 0px !important;
    }
    #fb5 .turn-page.even .fb5-cont-page-book > .fb5-gradient-page{
        cursor: pointer;
    }
    @media (max-width: 800px){
        #fb5 #fb5-all-pages .fb5-container-pages{
            bottom: 35%;
            top: auto !important;
            height:60px !important;
        }
        .stat-item.follow{
            top: 20px;x
        }
        #wo_post_stat_button {
            margin: 1px -15px 0;
            left: 19px !important;
            width: calc(100% + 30px);
            top: 40px;
        }
        .sliderUl{
            bottom: 35%;
        }
        #fb5-book{
            top: 65px;
        }
        #fb5-ajax.fullScreen, #fb5-ajax[data-template="true"]{
            max-width: 100%;
        }
        .comment-inner-middle {
            position: absolute;
            top: 75px;
            z-index: 999999;
            border-radius: 4px;
            left: 1px !important;
        }
        .sliderUl{
            height: 70px;
        }
        .sliderUl ul li img {
            max-height: 60px;
        }
        .wo_imagecombo_lbox .comment-section{
            height: auto !important;
            bottom: 0px;
            position: absolute;
            top: auto;
            max-height: 35%;
            max-width: 100%;
            overflow: hidden scroll;
            display:noe;
        }
        #fb5-ajax.fullScreen, #fb5-ajax[data-template="true"]{
            right: 0px !important;
        }
        #fb5 #fb5-button-back{
            botton: auto;
            top: 50px;
        }
        #fb5 .fb5-menu#fb5-center{
            width: auto;
            margin-top: 9px;
            top: 0px;
            position: absolute;
            max-width: 100%;
            left: 18% !important;
        }
        #fb5 .fb5-menu#fb5-center ul li{
            display: inline-block;
            width: auto;
        }
        #perImageModal .comment-inner-middle {
            top: 99px;
        }
    }
    
    
    
    
</style>
<!--<div data-test="i am here"  class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div>-->
<div class="lightbox-content post wo_imagecombo_lbox lightpost-<?php echo $wo['story']['id'];?>" id="post-<?php echo $wo['story']['id'];?>" data-post-id="<?php echo $wo['story']['id'];?>">
	     <div id="fb5-ajax" data-cat="your_book_name" data-template="true">
	            
	   
                
                
                
                
                
         <!-- BACKGROUND FLIPBOOK -->
         <div class="fb5-bcg-book"></div>
         <!--  BEGIN PRELOADER -->
         <div class="fb5-preloader"></div>
         <!-- END PRELOADER -->
         <!-- BEGIN STRUCTURE HTML FLIPBOOK -->      
         <div class="fb5" id="fb5">
            <!-- CONFIGURATION BOOK -->
            <section id="config">
               <ul>
                  <li key="page_width">520</li>
                  <!-- width for page -->
                  <li key="page_height">720</li>
                  <!-- height for page -->
                  <li key="gotopage_width">25</li>
                  <!-- width for field input goto page -->
                  <li key="zoom_double_click">1</li>
                  <!-- value zoom after double click -->
                  <li key="zoom_step">0.1</li>
                  <!-- zoom step ( if click icon zoomIn or zoomOut -->
                  <li key="toolbar_visible">true</li>
                  <!-- enabled/disabled toolbar -->
                  <li key="tooltip_visible">true</li>
                  <!-- enabled/disabled tooltip for icon -->
                  <li key="deeplinking_enabled">false</li>
                  <!-- enabled/disabled deeplinking -->  
                  <li key="lazy_loading_pages">false</li>
                  <!-- enabled/disabled lazy loading for pages in flipbook -->
                  <li key="lazy_loading_thumbs">false</li>
                  <!-- enabled/disabled lazdy loading for thumbs -->
                  <li key="double_click_enabled">true</li>
                  <!-- enabled/disabled double click mouse for flipbook -->                 
                  <li key="rtl">false</li>
                  <!-- enabled/disabled 'right to left' for eastern countries -->
                  <li key="pdf_url"></li>
                  <!-- pathway to a pdf file ( the file will be read live ) -->
                  <li key="pdf_scale">1</li>
                  <!-- to live a pdf file (if you want to have a strong zoom - increase the value) -->
                  <li key="page_mode">double</li>
                  <!-- value to 'single', 'double', or 'auto' -->
                  <li key="sound_sheet"></li>
                  <!-- sound for sheet -->
               </ul>
            </section>
            <!-- BEGIN BACK BUTTON -->
            <a href="#" id="fb5-button-back">&lt; Back </a>
            <!-- END BACK BUTTON -->                        
            <!-- BEGIN CONTAINER BOOK -->
           <!-- <section class="sliderUl">-->
          
           <!--    <ul>-->
           <!--                <img alt="" data-src="" src="">-->
           <!--             </li>-->
           <!--    </ul>-->
           <!--</section>-->
            <div id="fb5-container-book">
               <!-- BEGIN deep linking -->  
               <section id="fb5-deeplinking">
                  <ul>
                      <?php 
                           $k=0;
                            foreach ($postImages as $postImage) {
                          
                      
                      $k++;
                      ?>
                     <li data-address="page<?php echo $k; ?>" data-page="<?php echo $k; ?>"></li>
                     <?php } ?>
                     
                  </ul>
               </section>
               
               <!-- END deep linking -->  
               <!-- BEGIN ABOUT -->
               <section id="fb5-about">
               </section>
               <!-- END ABOUT -->
               <!-- BEGIN LINKS -->
               <section id="links">
               </section>
               <!-- END LINKS -->                         
               <!-- BEGIN PAGES -->
               
               <div id="fb5-book">
                   <?php 
                   $k=0;
                   foreach ($postImages as $postImage) {
                      
                      $k++;
                   ?>
                  <!-- begin page 1 -->          
                  <div data-toggle="modal" data-target="#perImageModal" style="background-image: url(<?php echo $postImage['imageUrl'] . "?cache=" . time();?>);">
                      
                      
                     <!-- container page book --> 
                     <div class="fb5-cont-page-book">
                        <!-- gradient for page -->
                        <div class="fb5-gradient-page"></div>
                        <!-- PDF.js --> 
                        <canvas id="canv<?php echo $k; ?>"></canvas>
                        <!-- description for page --> 
                        <div class="fb5-page-book">
                        </div>
                     </div>
                     <!-- end container page book --> 
                  </div>
                  <?php } ?>
                  <!-- end page 1 -->
               </div>
               <!-- END PAGES -->
            </div>
            <!-- END CONTAINER BOOK -->
            <!-- BEGIN FOOTER -->
            <div id="fb5-footer">
               <div class="fb5-bcg-tools"></div>
               <a id="fb5-logo" target="_blank" href="#">
               <img alt="" src="img/logo.png">
               </a>
               <div class="fb5-menu" id="fb5-left">
               </div>
               <div class="fb5-menu" id="fb5-center">
                  <ul>
                     <!-- icon_home -->
                     <li>
                        <a title="show home page" class="fb5-home"><i class="fa fa-home"></i></a>
                     </li>
                     <!-- icon download -->
                     
                     <!-- icon arrow left -->
                     <li>
                        <a title="prev page" class="fb5-arrow-left"><i class="fa fa-chevron-left"></i></a>
                     </li>
                     <!-- icon arrow right -->
                     <li>
                        <a title="next page" class="fb5-arrow-right"><i class="fa fa-chevron-right"></i></a>
                     </li>
                     <!-- icon_zoom_in -->                     
                     <li>
                        <a title="zoom in" class="fb5-zoom-in"><i class="fa fa-search-plus"></i></a>
                     </li>
                     <!-- icon_zoom_out -->                 
                     <li>
                        <a title="zoom out" class="fb5-zoom-out"><i class="fa fa-search-minus"></i></a>
                     </li>
                     <!-- icon_zoom_auto -->
                     <li>
                        <a title="zoom auto" class="fb5-zoom-auto"><i class="fa fa-search"></i></a>
                     </li>
                     
                      <!-- icon_allpages -->
                    <li>
                        <a title="show all pages" class="fb5-show-all"><i class="fa fa-list"></i></a>
                    </li>
                     
                     <!-- icon fullscreen -->                 
                     <li>
                        <a title="full/normal screen" class="fb5-fullscreen"><i class="fa fa-expand"></i></a>
                     </li>
                  </ul>
               </div>
               <div class="fb5-menu" id="fb5-right">
                  <ul>
                     <!-- icon page manager -->                 
                     <li class="fb5-goto">
                        <label for="fb5-page-number" id="fb5-label-page-number"></label>
                        <input type="text" id="fb5-page-number" style="width: 25px;"> 
                        <span id="fb5-page-number-two"></span>
                     </li>
                  </ul>
               </div>
            </div>
            <!-- END FOOTER -->
            <!-- BEGIN ALL PAGES -->
            <div id="fb5-all-pages" class="fb5-overlay">
               <section class="fb5-container-pages">
                  <div id="fb5-menu-holder">
                     <ul id="fb5-slider">
                        <!-- thumb 1 -->
                         <?php
                         $k=0;
                         foreach ($postImages as $postImage) {
                      
                      $k++;
                         ?>
                        <li class="<?php echo $k; ?>">
                           <img alt="" data-src="<?php echo $postImage['imageUrl']. "?cache=" . time();?>">
                        </li>
                        <?php } ?>
                       
                     </ul>
                  </div>
               </section>
            </div>
            <!-- END ALL PAGES -->           
            <!-- BEGIN SOUND FOR SHEET  -->
            <audio preload="auto" id="sound_sheet"></audio>
            <!-- END SOUND FOR SHEET -->
            <!-- BEGIN CLOSE LIGHTBOX  -->
            <div id="fb5-close-lightbox">
               <i class="fa fa-times pull-right"></i>
            </div>
            <!-- END CLOSE LIGHTBOX -->
         </div>
         <!-- END STRUCTURE HTML FLIPBOOK -->
      </div>
      
	<div class="comment-section">
		<div class="wow_lightbox_right">
			<div class="comment-section-inner">
				<div class="comment-inner-header">
					<div class="<?php echo Wo_RightToLeft('pull-right');?> close-lightbox" onclick="Wo_CloseLightbox();">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x" style="margin-top: 0px;width: 24px;height: 24px;"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
					</div>
					<div class="user-avatar <?php echo Wo_RightToLeft('pull-left');?>">
						<img src="<?php echo $wo['story']['publisher']['avatar'];?>" alt="">
					</div>
					<div class="user-name h5">
						<?php if (!isset($anonymous)) { ?>
						<span class="user-popover" data-type="<?php echo $wo['story']['publisher']['type']; ?>" data-id="<?php echo $wo['story']['publisher']['id']; ?>">
							<a href="<?php echo $wo['story']['publisher']['url'];?>?first_time=1"><?php echo $wo['story']['publisher']['name'];?></a>
						</span>
						<?php }else{ ?>
						<?php echo $wo['story']['publisher']['name'];?>
						<?php } ?>
					</div>
					<h6>
						<div class="time" style="color:#9197a3">
							<span class="ajax-time" title="<?php echo date('c',$wo['story']['time']); ?>"><?php echo Wo_Time_Elapsed_String($wo['story']['time']); ?></span>
						</div>
					</h6>
				</div>
				<div class="clear"></div>
				
			</div>
			<div class="comment-inner-footer lightbox-post-footer <?php echo ($wo['story']['comments_status'] == 0) ? 'hidden' : '';?>">
				<div id="hidden_inputbox_comment_lighbox"></div>
				<?php if($wo['story']['post_comments'] > 3 && $wo['story']['limited_comments'] === true && $wo['story']['comments_status'] == 1) { ?>
				<div class="view-more-wrapper load-more-comments" onclick="Wo_loadAllCommentslightbox(<?php echo $wo['story']['id']; ?>);">
					<span><?php echo $wo['lang']['view_more_comments'];?></span>
					<div class="ball-pulse <?php echo Wo_RightToLeft('pull-right');?>" style="line-height: 20px;"><div></div><div></div><div></div></div>
				</div>
				<?php } ?>
				<div class="comments-list comments-list-lightbox">
					<div class="comment comment-container"></div>
					<div class="comment comment-container"></div>
					<?php 
						foreach($wo['story']['get_post_comments'] as $wo['comment']) {
							echo Wo_LoadPage('comment/lightbox-content');
						}
					?>
					<?php  if (empty($wo['story']['get_post_comments'])) { ?>
					<div class="lightbox-no-comments">
						<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 58 58" style="enable-background:new 0 0 58 58;" xml:space="preserve"> <g> <path style="fill:#2CB742;" d="M33.224,10.494H13.776C6.168,10.494,0,16.661,0,24.27v11.345c0,7.608,6.392,13.879,14,13.879h0 v7.446c0,0.503,0.384,0.755,0.74,0.4l1.521-1.521c4.116-4.116,9.699-6.325,15.52-6.325h1.443C40.832,49.494,47,43.223,47,35.615 V24.27C47,16.661,40.832,10.494,33.224,10.494z"/> <g> <path style="fill:#9BC0EA;" d="M44.224,0.494H24.776c-6.371,0-11.717,4.332-13.292,10.206c0.747-0.125,1.509-0.206,2.292-0.206 h19.448C40.832,10.494,47,16.661,47,24.27v11.345c0,1.259-0.183,2.476-0.5,3.639C52.957,38.061,58,32.37,58,25.615V14.27 C58,6.661,51.832,0.494,44.224,0.494z"/> </g> <circle style="fill:#FFFFFF;" cx="12" cy="30.494" r="3"/> <circle style="fill:#FFFFFF;" cx="24" cy="30.494" r="3"/> <circle style="fill:#FFFFFF;" cx="36" cy="30.494" r="3"/> </g></svg>
						<h5><?php echo $wo['lang']['no_comments_found'];?></h5>
					</div>
					<?php } ?>
				</div>
			</div>
			<div class="lightbox-post-footer post-comments <?php echo ($wo['story']['comments_status'] == 0) ? 'hidden' : '';?>" id="post-comments-<?php echo $wo['story']['id'];?>"  <?php if ($wo['loggedin'] != true) { ?>onclick="location.href= '<?php echo $wo['config']['site_url'];?>'"<?php } ?>>
				<div class="post-commet-textarea dropup">
					<textarea class="form-control lighbox comment-textarea textarea" placeholder="<?php echo $wo['lang']['write_comment'];?>" type="text" onkeyup="Wo_RegisterComment(this.value,<?php echo $wo['story']['id']; ?>,<?php echo $wo['story']['publisher']['user_id']; ?>, event, <?php echo (!empty($wo['story']['publisher']['page_id'])) ? $wo['story']['publisher']['page_id'] : '0'; ?>)"  onkeydown="textAreaAdjust(this, 30,'lightbox')" dir="auto"></textarea>
					<span class="input-group-btn emo-comment dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" >
						<span class="btn btn-file">
							<svg fill="gray" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" class="feather feather-user-plus"><path d="M0 0h24v24H0z" fill="none"/><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z"/></svg>
						</span>
					</span>
					<div class="emo-post-container dropdown-menu" role="menu">
						<?php  
							foreach ($wo['emo'] as $code => $name) {
								$code   = $code;
								echo  '<span onclick="Wo_AddEmoToCommentInput(' . $wo["story"]["id"] . ', \'' . $code . '\', \'lightbox-post-footer\');"><i class="pointer twa-lg twa twa-' . $name . '"></i></span>'; 
							} 
						?>
					</div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>

<!-- PerImage Modals Starts -->
<div id="perImageModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- PerImage Modal content-->
    <div class="modal-content">
      <div class="modal-body text-center p-0">
            
            <!-- Close Button Starts -->
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <!-- Close Button Ends -->
            
            <!-- Image Starts -->
            <img src="https://revolus.com/upload/photos/2021/08/BwtDKQUIcEf5BQtdqkUG_23_2d76e27386ecf51351142f5056b09182_image.jpg?cache=1630966755" alt="" class="w-100"/>
            <!-- Image Ends -->
            
            <div class="comment-inner-middle" <?php if ($wo['loggedin'] != true) { ?>onclick="location.href= '<?php echo $wo['config']['site_url'];?>'"<?php } ?>>
				<div class="post-info">
					<div class="post-text">
						<p><?php echo $wo['story']['postText'];?></p>
					</div>
				</div>

				<div class="stats buttons" style="display: flex;">
					<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
						<div class="like-stat  stat-item post-like-status" style="width: inherit;">
							<span class="like-emo post-reactions-icons-<?php echo $wo['story']['id']; ?>" onclick="Wo_OpenPostReactedUsers(<?php echo $wo['story']['id']; ?>);">
								<?php echo Wo_GetPostReactions($wo['story']['id']);?>
							</span>
							<!-- <span class="like-details">Arkaprava Majumder and 1k others</span> -->
						</div>
					<?php }?>
				</div>
				<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
				<?php } ?>
				<div class="stats" id="wo_post_stat_button">
					<?php if ($wo['loggedin'] == true) { $wo['story']['viewmode'] = "lightbox";  echo Wo_LoadPage('buttons/like-wonder-2');}?>
				</div>
			</div>
			<div class="btn btn-default stat-item follow mb-10" title="Follow" onclick="">
			    <button>+</button>
                <span class="like-btn-mobile"></span>
            </div>
			<div class="btn btn-default stat-item share mb-10" title="Share" onclick="Wo_SharePostOn(<?php echo $wo['story']['id']; ?>,329,'timeline')">
                
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<g>
	<polygon style="fill:#0095FF;" points="177.47,244.428 162.118,218.646 333.856,115.459 349.208,141.24 	"/>
	<polygon style="fill:#0095FF;" points="332.274,401.58 166.791,317.011 180.326,290.233 345.81,374.803 	"/>
</g>
<g>
	<path style="fill:#00ABE9;" d="M406,0c-49.501,0-90,40.499-90,90c0,49.499,40.499,90,90,90s90-40.501,90-90
		C496,40.499,455.501,0,406,0z"/>
	<path style="fill:#00ABE9;" d="M406,332c-49.501,0-90,40.499-90,90c0,49.499,40.499,90,90,90s90-40.501,90-90
		C496,372.499,455.501,332,406,332z"/>
	<path style="fill:#00ABE9;" d="M106,181c-49.501,0-90,40.499-90,90c0,49.499,40.499,90,90,90s90-40.501,90-90
		C196,221.499,155.501,181,106,181z"/>
</g>
<g>
	<path style="fill:#0095FF;" d="M496,422c0,49.499-40.499,90-90,90V332C455.501,332,496,372.499,496,422z"/>
	<path style="fill:#0095FF;" d="M406,180V0c49.501,0,90,40.499,90,90C496,139.499,455.501,180,406,180z"/>
	<path style="fill:#0095FF;" d="M196,271c0,49.499-40.499,90-90,90V181C155.501,181,196,221.499,196,271z"/>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

                <span class="like-btn-mobile"></span>
            </div>
            <div class="btn btn-default stat-item comment mb-10" title="Comment" onclick="">
                <svg fill="gray" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" class="feather feather-user-plus"><path d="M0 0h24v24H0z" fill="none"/><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z"/></svg>
                <span class="like-btn-mobile"></span>
            </div>
            
      </div>
    </div>
  </div>
</div>
<!-- PerImage Modals Ends -->


<!--<script src="https://revolus.com/themes/wowonder/javascript/script.js?version=3.0.4"></script>-->
<script src="https://revolus.com/assets/js/jquery.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://revolus.com/assets/js/turn.js"></script>
<script src="https://revolus.com/assets/js/wait.js"></script>
<script src="https://revolus.com/assets/js/jquery.mousewheel.js"></script>
<script src="https://revolus.com/assets/js/jquery.fullscreen.js"></script>
<script src="https://revolus.com/assets/js/jquery.address-1.6.min.js"></script>
<script src="https://revolus.com/assets/js/pdf.js"></script>
<script src="https://revolus.com/assets/js/onload.js"></script>
<script>




$(document).ready(function(){
    setTimeout(function(){ 
        $(".fb5-show-all").click();
    }, 3000);
    $(".comment-inner-middle").click(function(event){
       $('#perImageModal ul.reactions-box').fadeIn();
       event.stopPropagation();
    //   e.stopPro
    });
});

// document.getElementByClassName("fb5-show-all").click();


$(document).keydown(function(e) {
    if (e.keyCode == 27) {
        Wo_CloseLightbox();
    }
    $(".lighbox.textarea").triggeredAutocomplete({
       hidden: '#hidden_inputbox_comment_lighbox',
       source: Wo_Ajax_Requests_File() + "?f=mention",
       trigger: "@" 
    });
});
$( ".story-img" ).mouseover(function() {
  $( ".changer" ).fadeIn(200);
});
$( ".story-img" ).mouseleave(function() {
  $( ".changer" ).fadeOut(200);
});

function zoomin(id){
	var myImg = document.getElementById("wo_zoom_<?php echo $wo['story']['id'];?>");
	$(myImg).addClass("double_zoom");
	$('#draggableHelper').draggable({ cursor: "move", revert: true, disabled: false });
}
function zoomout(id){
	var myImg = document.getElementById("wo_zoom_<?php echo $wo['story']['id'];?>");
	$(myImg).removeClass("double_zoom");
	$('#draggableHelper').draggable({ disabled: true, revert: true });
}

var angle = 0;
function rotate(id){
	angle += 90;
	$('#wo_zoom_<?php echo $wo['story']['id'];?>').css({'transform': 'rotate(-' + angle + 'deg)'});
	$.get(Wo_Ajax_Requests_File(), {
		f: 'rotate_image',
		angle: angle,
		image: '<?php echo $wo['story']['id'];?>'
	}, function (data) {
		
	});
}
function Wo_SharePostOn(post_id, owner_id,type){

  if (!post_id) {
    return false;
  }
    
    $('#share_post_modal').modal('hide');
    $('#share_post_modal').remove();
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'get_share_post',post_id:post_id},
    })
    .done(function(data) {
      if (data.status == 200) {
        $('body').append(data.html);
        $('#SearchForInputPostId').val(post_id);
        $('#SearchForInputTypeId').val(owner_id);
        $('#share_post_modal').modal('show');
      }
    })
    .fail(function() {
    })
    .always(function() {
    });
    
}
</script>
