<div class="modal fade" id="audio-group-modal" role="dialog" data-backdrop="static" data-keyboard="false">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title" id="audio-group-title"> Audio Call</h4>
         </div>
            <div class="modal-body" id="audio-group-body"></div>
         <div class="modal-footer">
             <button type="button" class="btn btn-success" id="grpaudioclick">Answer</button>
            <button type="button" class="btn btn-danger cancel-call" id="grpaudiocancelclick">Ignore</button>
         </div>
      </div>
   </div>
</div>