<?php echo Wo_LoadPage('welcome/welcome-header');?>
<style>
	video { 
	    position: fixed;
	    top: 50%;
	    left: 50%;
	    min-width: 100%;
	    min-height: 100%;
	    width: auto;
	    height: auto;
	    z-index: -100;
	    transform: translateX(-50%) translateY(-50%);
	 	background: url('https://revolus.revolus.com/slider-img.jpg') no-repeat;
		background-size: cover;
		transition: 1s opacity;
	}
	div#welcomeheader {
    background-image: url(https://revolus.revolus.com/Images/Untitled-3.png) !important;
    background: color:none !important;
    height: 5vh;
    background-repeat: no-repeat;
    width: 100%;
    background-size: cover;
}
ul.dropdown-menu.dropdown-menu-right.wow_lang_select_menu {
    width: 12em;
    height: 20em;
    line-height: 2em;
    border: 1px solid #ccc;
    padding: 0;
    margin: 0;
    overflow: scroll;
    overflow-x: hidden;
}
</style>
<video poster="https://revolus.revolus.com/Video/Nebula - 25047 (1).mp4" id="bgvid" playsinline autoplay muted loop>
<source src="https://revolus.revolus.com/Video/Nebula - 25047 (1).mp4" type="video/webm">
<source src="https://revolus.revolus.com/Video/Nebula - 25047 (1).mp4" type="video/mp4">

</video>

<div class="wrapper">
	<div class="login forgot_pass fadeInUp animated animated_5">
		<form id="confirm-form" class="fadeInUp animated animated_9" method="post">
			<p class="title"><?php echo $wo['lang']['confirm_your_account']?></p>
			<p><?php echo $wo['lang']['sign_in_attempt']?></p>
			<p><?php echo $wo['lang']['we_have_sent_you_code']?></p>
			<div class="errors"></div>
			<div class="wow_form_fields">
				<label for="confirm_code">Confirmation code</label>
				<input id="confirm_code" name="confirm_code" type="text" autofocus />
			</div>
			<div class="login_signup_combo">
				<div class="login__">
					<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['confirm']?></button>
				</div>
				<div class="signup__"></div>
			</div>
		</form>
	</div>
</div>
<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#confirm-form');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=confirm_user_unusal_login',
    beforeSend: function() {
		working = true;$this.find('button').attr("disabled", true);
		$this.find('.add_wow_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
        $state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.add_wow_loader').removeClass('btn-loading');
        $state.html(data.errors);
      }
      working = false;
    }
  });
});
</script>