<?php if(!empty($wo['story']['blog_id'])) { ?>
	
	<?php $bbl = Wo_GetBlogs(array('limit' => 1), $wo['story']['blog_id']); ?>
	<?php //print_r($bbl[0]['thumbnail']); ?>
	
	<div class="post-fetched-url wo_post_fetch_blog" id="fullsizeimg">
		<a href="<?php echo !empty($bbl[0]['url']) ? $bbl[0]['url'] : '';?>">
			<?php if (isset($bbl[0]) && isset($bbl[0]['thumbnail']) && !empty($bbl[0]['thumbnail'])) {?>
				<div class="post-fetched-url-con">
					<img src="<?php echo $bbl[0]['thumbnail'];?>" alt="<?php echo isset($bbl[0]['thumbnail']['title']) ? $bbl[0]['thumbnail']['title'] : '';?>"/>
				</div>
			<?php } ?>
			<div class="fetched-url-text" style="display:none;">
				<div class="wow_post_blog_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f35d4d" d="M20,11H4V8H20M20,15H13V13H20M20,19H13V17H20M11,19H4V13H11M20.33,4.67L18.67,3L17,4.67L15.33,3L13.67,4.67L12,3L10.33,4.67L8.67,3L7,4.67L5.33,3L3.67,4.67L2,3V19A2,2 0 0,0 4,21H20A2,2 0 0,0 22,19V3L20.33,4.67Z"></path></svg></div>
				<h4><?php echo $wo['story']['blog']['title'];?></h4>
				<div class="description"><?php echo $wo['story']['blog']['description'];?></div>
			</div>
			<div class="clear"></div>
		</a>
	</div>
<?php } ?>