<div class="container-fluid">
    <div>
        <h3>Send Android Notifications To Users</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Notifications</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Send Android Notifications To Users</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <div id="alert"></div>
                    <form class="mass-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="url" name="url" class="form-control">
                                <label class="form-label">URL <small>Link used when user clicks on the notification</small></label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <textarea name="description" id="description" class="form-control" cols="30" rows="5"></textarea>
                                <label class="form-label">Notification Text</label>
                            </div>
                        </div>
                        
                        <div class="notifications-users-list"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <input type="reset" class="hidden">
                        <input type="text" name="notifc-users" class="hidden" id="notifc-users">
                        <input type="reset" id="reset-notif-form" class="hidden">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Send Notifications</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
        	<div class="notif-selected-users card hidden"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
jQuery(document).ready(function($) {

  $('.mass-settings').ajaxForm({
	 url: Wo_Ajax_Requests_File() + '?f=android_notification&s=send',
	 type:"POST",
	 dataType:'json',
	 beforeSend: function() {
	   $('.mass-settings').find('button').text('Please wait..');
	 },
	 success: function(data) {
	   if (data['status'] == 200) {
		 $("#alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
		 $(".notifications-users-list").empty();
		 $(".notif-selected-users").empty();
		 $(".notif-selected-users").addClass('hidden');
	   } else if (data['status'] == 304) {
		 $("#alert").html('<div class="alert alert-danger">'+ data['message'] +'</div>');
	   } 
	   $('.mass-settings').find('button').text('Send Notifications');
  }});
});
</script>
</script>